---
# Source: commons-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commons-operator-serviceaccount
  labels:
    helm.sh/chart: commons-operator-0.1.0-nightly
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.1.0-nightly"
    app.kubernetes.io/managed-by: Helm
---
# Source: commons-operator/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: commons-operator-clusterrolebinding
  labels:
    helm.sh/chart: commons-operator-0.1.0-nightly
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.1.0-nightly"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: commons-operator-serviceaccount
    namespace: kuttl-test-enabling-platypus
roleRef:
  kind: ClusterRole
  name: commons-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
